version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
